/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 LTile.glb --transform 
Files: LTile.glb [7.43KB] > C:\Users\Hyunho\Documents\업무\수습\labyrinth\frontend\src\assets\LTile-transformed.glb [3.46KB] (53%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LTile(props) {
  const { nodes, materials } = useGLTF('/LTile-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group  >
        <mesh geometry={nodes.Cube.geometry} material={materials.floor} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.outside} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.wall_color} />
      </group>
    </group>
  )
}

useGLTF.preload('/LTile-transformed.glb')
