/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 meeple.glb --transform 
Files: meeple.glb [134.93KB] > C:\Users\Hyunho\Documents\업무\수습\labyrinth\frontend\src\assets\meeple-transformed.glb [11.71KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Meeple(props) {
  const { nodes, materials } = useGLTF('/meeple-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube000.geometry} material={materials.Material} position={[2.578, 0.443, 0.01]} rotation={[3.001, 0, Math.PI]} scale={[0.111, 0.103, 0.131]} />
    </group>
  )
}

useGLTF.preload('/meeple-transformed.glb')
