/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 oTile.glb --transform 
Files: oTile.glb [7.45KB] > C:\Users\Hyunho\Documents\업무\수습\labyrinth\frontend\src\assets\oTile-transformed.glb [1.96KB] (74%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function OTile(props) {
  const { nodes, materials } = useGLTF('/oTile-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.flor_tile.geometry} material={materials.PaletteMaterial001}   />
    </group>
  )
}

useGLTF.preload('/oTile-transformed.glb')
