/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 oTile2.glb --transform 
Files: oTile2.glb [7.33KB] > C:\Users\Hyunho\Documents\업무\수습\labyrinth\frontend\src\assets\oTile2-transformed.glb [4KB] (45%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function OTile2(props) {
  const { nodes, materials } = useGLTF('/oTile2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.109, 0]} scale={[1, 0.1, 1]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.floor} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.outside} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['outside.001']} />
        <mesh geometry={nodes.Cube_4.geometry} material={nodes.Cube_4.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/oTile2-transformed.glb')
