/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 meeple2.glb --transform 
Files: meeple2.glb [134.9KB] > C:\Users\Hyunho\Documents\업무\수습\labyrinth\frontend\src\assets\meeple2-transformed.glb [11.72KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Meeple2(props) {
  const { nodes, materials } = useGLTF('/meeple2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube000.geometry} material={materials.Material} position={[-7.21, 0.548, 5.10]} rotation={[3.001, 0, Math.PI]} scale={[0.111, 0.103, 0.131]} />
    </group>
  )
}

useGLTF.preload('/meeple2-transformed.glb')
